name: snpe
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.14
  - python=3.10.14
  - readline=8.2
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - alembic==1.13.2
      - ansi2html==1.9.2
      - astunparse==1.6.3
      - attrs==23.2.0
      - bcrypt==4.2.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - cffi==1.17.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmaes==0.11.0
      - coloredlogs==15.0.1
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cryptography==43.0.0
      - cycler==0.12.1
      - dash==2.12.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==4.4.2
      - exceptiongroup==1.2.2
      - flask==2.2.5
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - gast==0.4.0
      - google-auth==2.33.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.65.4
      - h5py==3.11.0
      - humanfriendly==10.0
      - idna==3.7
      - iniconfig==2.0.0
      - invoke==2.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.0
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.12.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - lxml==4.6.3
      - mako==1.1.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1.post1
      - mdurl==0.1.2
      - mock==3.0.5
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - onnx==1.16.1
      - onnxruntime==1.18.0
      - onnxruntime-gpu==1.18.1
      - onnxsim==0.4.36
      - opencv-python==4.5.4.58
      - opt-einsum==3.3.0
      - optuna==3.3.0
      - packaging==24.0
      - pandas==2.0.1
      - paramiko==3.4.0
      - pathlib2==2.3.6
      - pillow==10.2.0
      - pip==24.2
      - plotly==5.20.0
      - pluggy==1.5.0
      - protobuf==3.20.2
      - psutil==6.0.0
      - pyaml==24.7.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pygments==2.18.0
      - pynacl==1.5.0
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==5.3
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retrying==1.3.4
      - rich==13.7.1
      - rpds-py==0.20.0
      - rsa==4.9
      - scikit-learn==1.5.1
      - scikit-optimize==0.9.0
      - scipy==1.10.1
      - six==1.16.0
      - sqlalchemy==2.0.32
      - sympy==1.13.1
      - tabulate==0.8.5
      - tenacity==9.0.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - tflite==2.3.0
      - threadpoolctl==3.5.0
      - tomli==2.0.1
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchvision==0.14.1
      - tqdm==4.66.5
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - xlsxwriter==1.2.2
